spring:
  application:
    name: meal-management-api

  datasource:
    url: jdbc:mysql://localhost:3306/meal
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Swagger Setting
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs